MODEL:
  NUM_KEYPOINTS: 1024

DATASET:
  TASK: 'object'
  DATA_SOURCE: 'ho3d'
  DATA_ROOT: 'data/ho3d'
  JSON_PATH: 'assets/ho3d_test_3000/ho3d_test.json'

  MAX_ANGLE_ERROR: 45

TRAINER:
  EPOCHS: 200
  LEARNING_RATE: 0.00005
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  PCT_START: 0.3
  N_SAMPLES_PER_SUBSET: 4000
  