DATASET:
  DATA_SOURCE: 'linemod'
  DATA_ROOT: 'data/lm'

  OBJECT_ID: 8
  MIN_VISIBLE_FRACT: 0.5
  MAX_ANGLE_ERROR: 30

TRAINER:
  EPOCHS: 120
  LEARNING_RATE: 0.0002
  BATCH_SIZE: 32
  NUM_WORKERS: 8
