MODEL:
  NUM_KEYPOINTS: 1200

DATASET:
  DATA_SOURCE: 'linemod'
  DATA_ROOT: 'data/lm'
  JSON_PATH: 'assets/linemod_test_1500/linemod_test.json'

  MIN_VISIBLE_FRACT: 0.75
  MAX_ANGLE_ERROR: 45

TRAINER:
  EPOCHS: 200
  LEARNING_RATE: 0.00002
  BATCH_SIZE: 32
  NUM_WORKERS: 8
  PCT_START: 0.3
  N_SAMPLES_PER_SUBSET: 200
  